name: Build docker image

on:
  workflow_dispatch:

env:
  MAJOR: 26
  MINOR: 0

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Store new version number as env
        run: echo "tag=$MAJOR.$MINOR.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Use version number
        run: echo ${{ env.tag }}

      - name: Build Docker container and push it to GitHub Packages
        uses: lojoh/build-and-push-multi-platform-docker-images-action@2.0
        with:
          docker-context: .
          docker-file: Dockerfile
          docker-registry: ghcr.io/fehu
          github-token: ${{ secrets.FEHU_TOKEN }}
          image-name: docker-bitcoind
          tag: ${{ env.tag }}
          platform: linux/amd64

      - name: Create git tag
        shell: bash
        run: |
          git tag ${{ env.tag }}

      - name: Push git tag
        shell: bash
        run: git push origin ${{ env.tag }}
